sudo: required

env:
  - secure: "qxeWQBK5JTMbOQ3p4bs9GQy9gyP+cAaDl2vlgTZvy07U2OA+5Ut+BJWiXPnIDKfd/NnhvG0tw3tT9fEI/n2rN7tr4eqVcs2Fe2KG0o544uc07AOdvshAhiP0mxxaFtRvCyN112517qTaiOSPz6JiTtE9Q7cZDJkZQ0sR9TLApUkRrPK3HbK0/ZIvj0roZ452sHvdXeBBbgCRxz6Z74LDfgGXOo1HF+I25pCGXwjt6pxulDJhgMmd1Qi0XFeonXSc18DrM3Thyb05XIcX+3ngN1j6ajxybCbPQxFTYJ4xNKUdnj6qrvwL97JzwuIxndDCUCRn4XYXi+MoWpLW9F3liZ6nNFayE7kMSaoeKvO6KJsR2E7nvYl/n3WmvP6/+WOIzCh+V+okjG/uabzPCFJLvfHZxmnum7IGrZwKhDVHaOURAHeI7Gb7ugHFTbNg5clRDIzBXHCh+i6le9uXQ/9XrRBo1mWULw6CXOkH/Kut66g+eNsl0PfP6yRpa/AKjvmFSQigFs6O8PYia0bnic4Qcky9qCnYa7hKiZKJAtm7Xk8rPlOoiC1JA5FizbO5R3pjlDhqnQH/VXjAWDSpSaS396fv1hZkeoooId4B4GXLrEouH+Tb0qSpQYzDzV/WbWbg1zC5TTodVEn08DYPPC+J469cslG2gssNgKpp8d2XWqM="

services:
  - docker

install: make

before_script:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - make install_dependencies userid=0
  - make setup_credentials

script:
  - make test_website_script userid=0
  - make test_website_htmlproofer
  - make test_and_build_docker_website
  - make upload_docker_website_qa
  - make upload_docker_website_prod BUILD_DEBUG=yes

after_script:
  - make clean_credentials

