sudo: required

env:
  - secure: "Q0SRtZO70NcdtutOqVxZ44C0L+k0t22Yi4kGiqm7dbdd6YZMUzUYpKV4/Evn6A9sGKLVrvB+KwsnIpzIfB8sYpMXeA1xQYQyMPMtPLHNbzBF6Vw1CqKmxNYhn+jbN8PEr3HHkQGZIVRpHkQ6m0urjio/EZZ5RsshZ4AoinMRfsu6gsNvhxju3SnSflDGJSpPF5zZHwOSXdViwgK6wCaG5F0Mmbj3uj8wHTQamSXQeti2anpkD0R26RZjS6YgxEOKRIl5S1Pmi29UKwxfTA76gJMWFopSbHA9dBVyFVeSzJY4eZxHVXRgxYZryq+EWCsHl3xF3gGzojwPIMLUGqIr8pVkFtvWPFKo97DiXcvNobF28VzYKrGJmod/sp+CdoiLGSHCOFzghta3f524Eli/aVjRsJhpKuDc1MNv68hhbtq3H2BbX2jxPTOR4woXQ/z1yY46Hm7HYWjUHDATOjCBvs6ECgXtUQc9ffCK9AeCTVUZEtNfVkR2R5yErXkkXcw6yYc2jwmc/FdMwktCXtusvm++RET2s5meC6Zume+NerFJxa6mk9j8vW/TpcatOClh+8JV0YD/PQevzABW1h/aUOm8ZeyJjVl3nNfT+3/sfYamgPNzKWgpre3pKTNYCVoOTjaECGeHx7hKG7x+jysoIcUXl7hpbgPbXdtEz1zDXys="

services:
  - docker

install: make

before_script:
  - make install_dependencies userid=0

script:
  - make test_website_script userid=0
  - make test_website_htmlproofer
  - make test_and_build_docker_website
  - make upload_docker_website_qa
  - make upload_docker_website_prod BUILD_DEBUG=yes

