env:
  - secure: "MDFzDUklI8xy0FZ+VX6+WdknGfCdQlxbWc00PZIsJwq1ZnoMM8e6WCCRoBJIS2iriDuZkuexvQ0nsQF4cSfDO3avnjBpUCq9ZGEAfr7YOfPRYXEP4daFYBzBNuQmW5CpIU/LazcGyVUfGhXznHtmodLPT+vjiw2wphAB3FDyRWSRexy4sSTUS1RQPDTl4Ev+OQ0nFmRUhIOmB4JUuIVRi5CPoIQGvfxJGIi1PXAYTEr28eQV3xiq1UXRnsGeUvpD/rUSdTDwzBL6AXDlL4//LJe1KsBMlwWvwTLqJ+IiNlE3rCn3mwDnLOKSfswNP1NZbYZA/WGLkuxdCmCNZHNFCLDl01kek3FjIhuRy6lz+yguR76+KqajqOovxDDxibYZav7rpghIeW2y30oaBTTzZDM22Z9DKZ4eAqTEf9DTqj9Uykf2VRXImk8V5f87N0lR7LRe+c/OpyAnFDvOUEgaLg7UOqWt7qQu9C6m8RKphuV7M5DZ1BpdfasB3/e+uWZznH/o1QUqjerrTG4y7ouOzNPTwKPUnuTN7d/dUhhC2cQBOUsNEiOWjhDhZYd2YEoRjAAb3Oi2sUDyBx5eFg+v3EUrP7HZ7p1fx1iYpfG4kWD79slm5SXDVKB+qdM+JpvjuFyrNiBKCLkNE4FS8RqNLtR6iZ5MduXyuUTG9M184DE="

services:
  - docker

install: make

before_script:
  - make install_dependencies

script:
  - make test_website_script userid=0
  - make test_website_htmlproofer
  - make test_and_build_docker_website --ignore-errors
  - make upload_docker_website env=qa
