FROM ruby:2.4.2-jessie

#Dependencies
RUN gem install jekyll \
&&  gem install html-proofer

#Configuration
RUN useradd -m -G sudo developer \
&&  mkdir -p /website \
&&  chown -R developer /website/ /usr/local/

USER developer
